In [1]:
import pandas as pd

In [4]:
# Inner Join

df1 = pd.DataFrame({
    'id' : [1, 2, 3, 4],
    'name' : ['Anushka', 'Rahul', 'Raj', 'Riya'],
    'age' : [21, 23, 56, 89]
})
df2 = pd.DataFrame({
    'id' : [3, 4, 5, 6],
    'name' : ['Ravi', 'Rahul', 'Surya', 'Raj'],
    'age' : [23, 40, 50, 89]
})
df3 = pd.merge(df1, df2, on = 'id', how = 'inner')

df3.rename(columns = {'name_x' : 'table_name1'}, inplace = True)

print(df3)

   id table_name1  age_x name_y  age_y
0   3         Raj     56   Ravi     23
1   4        Riya     89  Rahul     40

In [5]:
# Left Join

df1 = pd.DataFrame({
    'id' : [1, 2, 3, 4],
    'name' : ['Anushka', 'Rahul', 'Raj', 'Riya'],
    'age' : [21, 23, 56, 89]
})
df2 = pd.DataFrame({
    'id' : [3, 4, 5, 6],
    'name' : ['Ravi', 'Rahul', 'Surya', 'Raj'],
    'age' : [23, 40, 50, 89]
})
df3 = pd.merge(df1, df2, on = 'id', how = 'left')

# df3.rename(columns = {'name_x' : 'table_name1'}, inplace = True)

print(df3)

   id   name_x  age_x name_y  age_y
0   1  Anushka     21    NaN    NaN
1   2    Rahul     23    NaN    NaN
2   3      Raj     56   Ravi   23.0
3   4     Riya     89  Rahul   40.0

In [6]:
# Right Join

df1 = pd.DataFrame({
    'id' : [1, 2, 3, 4],
    'name' : ['Anushka', 'Rahul', 'Raj', 'Riya'],
    'age' : [21, 23, 56, 89]
})
df2 = pd.DataFrame({
    'id' : [3, 4, 5, 6],
    'name' : ['Ravi', 'Rahul', 'Surya', 'Raj'],
    'age' : [23, 40, 50, 89]
})
df3 = pd.merge(df1, df2, on = 'id', how = 'right')

# df3.rename(columns = {'name_x' : 'table_name1'}, inplace = True)

print(df3)

   id name_x  age_x name_y  age_y
0   3    Raj   56.0   Ravi     23
1   4   Riya   89.0  Rahul     40
2   5    NaN    NaN  Surya     50
3   6    NaN    NaN    Raj     89

In [8]:
# Outer Join

df1 = pd.DataFrame({
    'id' : [1, 2, 3, 4],
    'name' : ['Anushka', 'Rahul', 'Raj', 'Riya'],
    'age' : [21, 23, 56, 89]
})
df2 = pd.DataFrame({
    'id' : [3, 4, 5, 6],
    'name' : ['Ravi', 'Rahul', 'Surya', 'Raj'],
    'age' : [23, 40, 50, 89]
})
df3 = pd.merge(df1, df2, on = 'id', how = 'outer')

# df3.rename(columns = {'name_x' : 'table_name1'}, inplace = True)

print(df3)

   id   name_x  age_x name_y  age_y
0   1  Anushka   21.0    NaN    NaN
1   2    Rahul   23.0    NaN    NaN
2   3      Raj   56.0   Ravi   23.0
3   4     Riya   89.0  Rahul   40.0
4   5      NaN    NaN  Surya   50.0
5   6      NaN    NaN    Raj   89.0

In [9]:
# Cross Join

df1 = pd.DataFrame({
    'id' : [1, 2, 3, 4],
    'name' : ['Anushka', 'Rahul', 'Raj', 'Riya'],
    'age' : [21, 23, 56, 89]
})
df2 = pd.DataFrame({
    'id' : [3, 4, 5, 6],
    'name' : ['Ravi', 'Rahul', 'Surya', 'Raj'],
    'age' : [23, 40, 50, 89]
})
df3 = pd.merge(df1, df2, how = 'cross')

# df3.rename(columns = {'name_x' : 'table_name1'}, inplace = True)

print(df3)

    id_x   name_x  age_x  id_y name_y  age_y
0      1  Anushka     21     3   Ravi     23
1      1  Anushka     21     4  Rahul     40
2      1  Anushka     21     5  Surya     50
3      1  Anushka     21     6    Raj     89
4      2    Rahul     23     3   Ravi     23
5      2    Rahul     23     4  Rahul     40
6      2    Rahul     23     5  Surya     50
7      2    Rahul     23     6    Raj     89
8      3      Raj     56     3   Ravi     23
9      3      Raj     56     4  Rahul     40
10     3      Raj     56     5  Surya     50
11     3      Raj     56     6    Raj     89
12     4     Riya     89     3   Ravi     23
13     4     Riya     89     4  Rahul     40
14     4     Riya     89     5  Surya     50
15     4     Riya     89     6    Raj     89

In [11]:
# Concat function

df1 = pd.DataFrame({
    'id' : [1, 2, 3, 4],
    'name' : ['Anushka', 'Rahul', 'Raj', 'Riya'],
    'age' : [21, 23, 56, 89]
})
df2 = pd.DataFrame({
    'id' : [3, 4, 5, 6],
    'name' : ['Ravi', 'Rahul', 'Surya', 'Raj'],
    'age' : [23, 40, 50, 89]
})
df3 = pd.concat([df1, df2])

print(df3)

   id     name  age
0   1  Anushka   21
1   2    Rahul   23
2   3      Raj   56
3   4     Riya   89
0   3     Ravi   23
1   4    Rahul   40
2   5    Surya   50
3   6      Raj   89

In [14]:
# drop_duplicate

df1 = pd.DataFrame({
    'id' : [1, 2, 3, 4],
    'name' : ['Anushka', 'Rahul', 'Raj', 'Riya'],
    'age' : [21, 23, 56, 89]
})
df2 = pd.DataFrame({
    'id' : [3, 4, 5, 6],
    'name' : ['Ravi', 'Rahul', 'Surya', 'Raj'],
    'age' : [23, 40, 50, 89]
})
df3 = pd.concat([df1, df2])

df3 = df3.drop_duplicates(subset = ['id', 'name'], keep = 'first')   # , inplace = True (another parameter)

print(df3)

   id     name  age
0   1  Anushka   21
1   2    Rahul   23
2   3      Raj   56
3   4     Riya   89
0   3     Ravi   23
1   4    Rahul   40
2   5    Surya   50
3   6      Raj   89

In [15]:
df = pd.read_csv('student_data.csv')

In [17]:
df.pivot_table(columns = "placement_status", index = 'sleep_hours', values = 'exam_score', aggfunc = 'mean')

placement_status  Not Placed     Placed
sleep_hours
4                  59.424160  90.483113
5                  58.306079  91.085519
6                  60.971968  91.819595
7                  59.650121  92.279986
8                  60.091122  93.062072
9                  61.181129  92.987227

In [18]:
df.pivot_table(columns = 'study_hours', index = 'sleep_hours', values = 'assignments_completed', aggfunc = 'mean')

study_hours,1,2,3,4,5,6,7,8,9,10,11
sleep_hours,,,,,,,,,,,
4,9.980392,10.283784,10.166667,9.529801,10.187050,10.530612,9.836158,10.486111,9.950000,9.114458,9.662420
5,10.231707,9.837838,10.051948,9.706667,9.679487,10.604651,11.151515,10.118519,10.616279,9.886228,9.863946
6,10.566265,10.417808,10.229299,9.694805,10.066667,10.131737,9.934307,10.601399,9.868966,9.375000,9.291045
7,11.026846,9.166667,9.440252,10.007143,9.888889,9.606250,10.750000,8.380368,11.130719,10.506024,9.741007
8,9.303448,8.741935,9.807692,10.204545,9.843373,10.105960,10.057325,9.967742,10.633987,10.060000,10.220000
9,10.245283,9.646667,9.968944,9.582822,10.308725,9.744681,10.355828,9.926667,10.085714,9.185185,10.141844

In [ ]:
# Homework

# Leetcode Ques:

# 1327
# 511
# 586
# 1050
# 175
# 181
# 182
# 262
# 184
# 185
# 1179