In [39]:
import pandas as pd

In [40]:
dct = {
    'name' : ['Anu', 'Riya', 'Suga', 'Jimin'],
    'age' : [22, 25, 32, 30],
    'roll' : [1, NaN, 3, 4]
}

dF = pd.DataFrame(dct)
dF1 = pd.DataFrame(dct)

display(dF)
display(dF1)

    name  age  roll
0    Anu   22     1
1   Riya   25     2
2   Suga   32     3
3  Jimin   30     4

    name  age  roll
0    Anu   22     1
1   Riya   25     2
2   Suga   32     3
3  Jimin   30     4

In [41]:
df = pd.read_csv('student_data.csv')
df
# print(df.head(3))
#print(df.tail(3)) # last 3 values
#print(df.shape) # rows and columns
#print(df.info) # dataframe metadata(file info - columns,datatypes,filetype)
#df.describe() - #statstical summary(mean.med,quartiles,std,min,max)
#df.columns - name of columns

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [42]:
df.index

RangeIndex(start=0, stop=10000, step=1)

In [43]:
df[['study_hours','internet_usage']]

      study_hours  internet_usage
0               7               7
1               4               3
2              11               6
3               8               8
4               5               6
...           ...             ...
9995            2               7
9996            7               9
9997           10               5
9998           10               5
9999            2              11

[10000 rows x 2 columns]

In [44]:
df.iloc[0]

study_hours                   7
attendance                   56
sleep_hours                   8
internet_usage                7
assignments_completed        10
previous_score               62
exam_score                100.0
placement_status         Placed
Name: 0, dtype: object

In [45]:
df.iloc[0:5]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed

In [46]:
df.loc[df['study_hours']==11,['study_hours']]

      study_hours
2              11
9              11
10             11
29             11
30             11
...           ...
9969           11
9971           11
9978           11
9979           11
9988           11

[868 rows x 1 columns]

In [47]:
df.loc[df['study_hours'] == 11, ['study_hours', 'sleep_hours']].iloc[4: 8]

     study_hours  sleep_hours
30            11            5
91            11            9
98            11            6
116           11            7

In [48]:
df.loc[4]

study_hours                   5
attendance                   52
sleep_hours                   8
internet_usage                6
assignments_completed         8
previous_score               40
exam_score                78.82
placement_status         Placed
Name: 4, dtype: object

In [49]:
df.loc[df["assignments_completed"] == 8].iloc[[1]]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
4,5,52,8,6,8,40,78.82,Placed

In [50]:
df[df["assignments_completed"] > 15]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
8,7,72,8,5,18,48,96.81,Placed
12,5,52,6,9,17,89,95.36,Placed
22,2,47,8,2,19,87,98.66,Placed
23,5,88,6,3,16,43,100.00,Placed
28,1,44,9,1,20,44,76.12,Placed
...,...,...,...,...,...,...,...,...
9978,11,92,8,2,16,79,100.00,Placed
9979,11,78,9,5,18,82,100.00,Placed
9982,6,62,6,4,20,55,100.00,Placed
9983,6,92,6,10,18,62,83.24,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [51]:
df["age"] = 20
df

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status,age
0,7,56,8,7,10,62,100.00,Placed,20
1,4,69,5,3,8,56,100.00,Placed,20
2,11,60,7,6,10,45,100.00,Placed,20
3,8,99,9,8,4,55,90.17,Placed,20
4,5,52,8,6,8,40,78.82,Placed,20
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,20
9996,7,98,6,9,4,87,100.00,Placed,20
9997,10,44,8,5,10,37,95.94,Placed,20
9998,10,75,7,5,8,52,88.61,Placed,20
9999,2,70,6,11,16,52,78.96,Placed,20

In [52]:
df = df.rename(columns = {'assignments_completed' : 'assign_completed'})
df

,study_hours,attendance,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status,age
0,7,56,8,7,10,62,100.00,Placed,20
1,4,69,5,3,8,56,100.00,Placed,20
2,11,60,7,6,10,45,100.00,Placed,20
3,8,99,9,8,4,55,90.17,Placed,20
4,5,52,8,6,8,40,78.82,Placed,20
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,20
9996,7,98,6,9,4,87,100.00,Placed,20
9997,10,44,8,5,10,37,95.94,Placed,20
9998,10,75,7,5,8,52,88.61,Placed,20
9999,2,70,6,11,16,52,78.96,Placed,20

In [53]:
df.rename(columns = {'assignments_completed' : 'assign_completed'}, inplace = True)
print(df)

      study_hours  attendance  sleep_hours  internet_usage  assign_completed  \
0               7          56            8               7                10
1               4          69            5               3                 8
2              11          60            7               6                10
3               8          99            9               8                 4
4               5          52            8               6                 8
...           ...         ...          ...             ...               ...
9995            2          58            9               7                 8
9996            7          98            6               9                 4
9997           10          44            8               5                10
9998           10          75            7               5                 8
9999            2          70            6              11                16

      previous_score  exam_score placement_status  age
0                 62      100.00           Placed   20
1                 56      100.00           Placed   20
2                 45      100.00           Placed   20
3                 55       90.17           Placed   20
4                 40       78.82           Placed   20
...              ...         ...              ...  ...
9995              88       69.31       Not Placed   20
9996              87      100.00           Placed   20
9997              37       95.94           Placed   20
9998              52       88.61           Placed   20
9999              52       78.96           Placed   20

[10000 rows x 9 columns]

In [55]:
df.drop(columns=["age"])

,study_hours,attendance,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [62]:
df.dropna()

,study_hours,attendance,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status,age
0,7,56,8,7,10,62,100.00,Placed,20
1,4,69,5,3,8,56,100.00,Placed,20
2,11,60,7,6,10,45,100.00,Placed,20
3,8,99,9,8,4,55,90.17,Placed,20
4,5,52,8,6,8,40,78.82,Placed,20
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,20
9996,7,98,6,9,4,87,100.00,Placed,20
9997,10,44,8,5,10,37,95.94,Placed,20
9998,10,75,7,5,8,52,88.61,Placed,20
9999,2,70,6,11,16,52,78.96,Placed,20

In [60]:
df.sort_values(by="exam_score")

,study_hours,attendance,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status,age
8805,1,63,4,11,6,54,26.67,Not Placed,20
186,1,47,5,10,0,46,26.89,Not Placed,20
3141,1,55,8,8,5,40,27.82,Not Placed,20
7566,1,58,7,3,6,38,31.41,Not Placed,20
9499,2,64,5,10,6,37,31.43,Not Placed,20
...,...,...,...,...,...,...,...,...,...
0,7,56,8,7,10,62,100.00,Placed,20
1,4,69,5,3,8,56,100.00,Placed,20
2,11,60,7,6,10,45,100.00,Placed,20
9993,10,86,9,9,15,63,100.00,Placed,20
9996,7,98,6,9,4,87,100.00,Placed,20

In [61]:
df.sort_index()

,study_hours,attendance,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status,age
0,7,56,8,7,10,62,100.00,Placed,20
1,4,69,5,3,8,56,100.00,Placed,20
2,11,60,7,6,10,45,100.00,Placed,20
3,8,99,9,8,4,55,90.17,Placed,20
4,5,52,8,6,8,40,78.82,Placed,20
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,20
9996,7,98,6,9,4,87,100.00,Placed,20
9997,10,44,8,5,10,37,95.94,Placed,20
9998,10,75,7,5,8,52,88.61,Placed,20
9999,2,70,6,11,16,52,78.96,Placed,20

In [65]:
import numpy as np
dct = {
    'name' : ['Anu', 'Riya', 'Suga', 'Jimin'],
    'age' : [22, 25, 32, 30],
    'roll' : [1, np.nan, 3, 4]
}

dF = pd.DataFrame(dct)
dF

    name  age  roll
0    Anu   22   1.0
1   Riya   25   NaN
2   Suga   32   3.0
3  Jimin   30   4.0

In [66]:
dF.dropna()

    name  age  roll
0    Anu   22   1.0
2   Suga   32   3.0
3  Jimin   30   4.0

In [68]:
dF.isnull()

    name    age   roll
0  False  False  False
1  False  False   True
2  False  False  False
3  False  False  False

In [69]:
dF.notnull()

   name   age   roll
0  True  True   True
1  True  True  False
2  True  True   True
3  True  True   True

In [73]:
dF.fillna(2)

    name  age  roll
0    Anu   22   1.0
1   Riya   25   2.0
2   Suga   32   3.0
3  Jimin   30   4.0

In [77]:
dF["name"].unique()

array(['Anu', 'Riya', 'Suga', 'Jimin'], dtype=object)

In [78]:
dF.agg("sum")

name    AnuRiyaSugaJimin
age                  109
roll                 8.0
dtype: object